name : 'user-web'
port: 8021
user_srv:
  host: '192.168.0.14'
  port: 50058
  name: 'user-srv'

jwt:
  key: 'zrz31415926'

redis:
  host: '192.168.0.10'
  port: 6379
  expire: 300

consul:
  host: 192.168.0.10
  port: 8500
